[package]
name = "docup-lang"
version = "0.3.2"
edition = "2024"
authors = []
description = "DocUP compiler: compiles .du documents to standalone HTML5"
readme = "README.md"
license = "MIT"
repository = "https://github.com/pbarot2009/docup"
keywords = ["markup", "compiler", "html5", "parser", "docup"]
categories = ["command-line-utilities", "compilers", "text-processing"]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE*",
]

[lib]
name = "docup"
path = "src/lib.rs"

[[bin]]
name = "docup"
path = "src/main.rs"

[dependencies]
xarp = "0.1.2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
debug = false
incremental = false

[profile.dev]
opt-level = 0
debug = true
incremental = true
